### PR TITLE
remove node_modules

### PR DESCRIPTION
**Pull request by tiye**
It must be a mistake. `node_modules/` is not supposed to be here.

### CODE REVIEW

**Comment by naltatis** [comment]
No, its a conscious decision. You can argue for and against it, but I prefer having non binary dependencies checked in under version control. I agree with most of this points http://www.futurealoof.com/posts/nodemodules-in-git.html

**Comment by tiye** [comment]
`package.json` is designed to track the versions of packages.
Putting `node_modules` in a repo, is bad for me for some reasons:
- I have to clone the whole repo, it's huge.
- I have to upload it to server, rathar that install dependency on server, it's also huge
- if there's a problem found in your repo, I will actually not look into the modules
- I was confused, others will be confused too, it could be nice for you, though

I forked this repo and compiled a Chinese version:
http://jade-syntax.coffee-js.org/
I mainly wanted to make sure that my fork works.

**Comment by naltatis** [comment]
I agree that the size may be confusing at first. I like the reliability that I always compile with the modules I've tested with. Wether the dependencies have to be downloaded from npm or are embedded into the repo should make no difference in size or speed. But this is a very philosophical discussion ;)

It's very impressive to see a Chinese translation of this little project! I like that jade is becoming the template language of choice for so many people.

**Comment by tiye** [comment]
This project is very nice, so I think a Chinese one is also very interesting.
Yes, there are very people using Jade, even in Python or other communities who play with HTML.

**Comment by tiye** [comment]
Closing

**Pull request closed without merging**
